export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';

export const LOAD_MORE_CONTACTS_REQUEST = 'LOAD_MORE_CONTACTS_REQUEST';
export const LOAD_MORE_CONTACTS_SUCCESS = 'LOAD_MORE_CONTACTS_SUCCESS';
export const LOAD_MORE_CONTACTS_FAILURE = 'LOAD_MORE_CONTACTS_FAILURE';
